/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SheetSheetIdRouteImport } from './routes/sheet.$sheetId'
import { Route as FolderFolderIdRouteImport } from './routes/folder.$folderId'
import { Route as DocDocIdRouteImport } from './routes/doc.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetSheetIdRoute = SheetSheetIdRouteImport.update({
  id: '/sheet/$sheetId',
  path: '/sheet/$sheetId',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderFolderIdRoute = FolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdRoute = DocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/recent': typeof RecentRoute
  '/trash': typeof TrashRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/recent': typeof RecentRoute
  '/trash': typeof TrashRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/recent': typeof RecentRoute
  '/trash': typeof TrashRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites' | '/recent' | '/trash' | '/doc/$docId' | '/folder/$folderId' | '/sheet/$sheetId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/recent' | '/trash' | '/doc/$docId' | '/folder/$folderId' | '/sheet/$sheetId'
  id: '__root__' | '/' | '/favorites' | '/recent' | '/trash' | '/doc/$docId' | '/folder/$folderId' | '/sheet/$sheetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  RecentRoute: typeof RecentRoute
  TrashRoute: typeof TrashRoute
  DocDocIdRoute: typeof DocDocIdRoute
  FolderFolderIdRoute: typeof FolderFolderIdRoute
  SheetSheetIdRoute: typeof SheetSheetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$sheetId': {
      id: '/sheet/$sheetId'
      path: '/sheet/$sheetId'
      fullPath: '/sheet/$sheetId'
      preLoaderRoute: typeof SheetSheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$folderId': {
      id: '/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof FolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId': {
      id: '/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/doc/$docId'
      preLoaderRoute: typeof DocDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  RecentRoute: RecentRoute,
  TrashRoute: TrashRoute,
  DocDocIdRoute: DocDocIdRoute,
  FolderFolderIdRoute: FolderFolderIdRoute,
  SheetSheetIdRoute: SheetSheetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
