/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SheetSheetIdRouteImport } from './routes/sheet.$sheetId'
import { Route as FolderFolderIdRouteImport } from './routes/folder.$folderId'
import { Route as DocDocIdRouteImport } from './routes/doc.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetSheetIdRoute = SheetSheetIdRouteImport.update({
  id: '/sheet/$sheetId',
  path: '/sheet/$sheetId',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderFolderIdRoute = FolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdRoute = DocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/sheet/$sheetId': typeof SheetSheetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doc/$docId' | '/folder/$folderId' | '/sheet/$sheetId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doc/$docId' | '/folder/$folderId' | '/sheet/$sheetId'
  id: '__root__' | '/' | '/doc/$docId' | '/folder/$folderId' | '/sheet/$sheetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocDocIdRoute: typeof DocDocIdRoute
  FolderFolderIdRoute: typeof FolderFolderIdRoute
  SheetSheetIdRoute: typeof SheetSheetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$sheetId': {
      id: '/sheet/$sheetId'
      path: '/sheet/$sheetId'
      fullPath: '/sheet/$sheetId'
      preLoaderRoute: typeof SheetSheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$folderId': {
      id: '/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof FolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId': {
      id: '/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/doc/$docId'
      preLoaderRoute: typeof DocDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocDocIdRoute: DocDocIdRoute,
  FolderFolderIdRoute: FolderFolderIdRoute,
  SheetSheetIdRoute: SheetSheetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
